[project]
name = "memo-transcription-to-obsidian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.0.0",
    "rich>=13.0.0",
    "google-generativeai>=0.8.0",
]
